name: .NET Core

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x.x
        
    - name: Install dependencies
      run: dotnet restore mjm.nethelpers/mjm.nethelpers.sln
      
    - name: Test
      run: dotnet test mjm.nethelpers/mjm.nethelpers.tests/mjm.nethelpers.tests.csproj
      
    - name: Build and Pack
      run: dotnet pack mjm.nethelpers/mjm.nethelpers/mjm.nethelpers.csproj --configuration Release --no-restore /p:Version=${GITHUB_REF##*/} 
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: mjm.nethelpers
        # Directory containing files to upload
        path: mjm.nethelpers/mjm.nethelpers/bin/Release
    
    - name: Push to nuget
      run: dotnet nuget push mjm.nethelpers/mjm.nethelpers/bin/Release/mjm.nethelpers.${GITHUB_REF##*/}.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
    
